/* The following code was generated by JFlex 1.7.0 */

package Gramaticas;
import Grafica.OperadorInfo;
import java_cup.runtime.*;
import Gramaticas.sym;
import java.util.ArrayList;
    import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
    import java.util.Map;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>Lexico.jflex</tt>
 */
public class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\12\1\13\1\1\22\0\1\3\7\0\1\45"+
    "\1\46\1\44\1\43\1\47\1\14\1\10\1\11\1\6\11\7\1\0"+
    "\1\51\1\0\1\50\3\0\1\17\1\35\1\23\1\27\1\30\1\20"+
    "\1\15\1\54\1\22\1\36\1\4\1\25\1\34\1\32\1\26\1\33"+
    "\1\4\1\16\1\42\1\31\1\24\1\40\1\4\1\52\1\53\1\37"+
    "\4\0\1\5\1\0\1\17\1\35\1\23\1\27\1\30\1\20\1\15"+
    "\1\54\1\22\1\36\1\4\1\25\1\34\1\32\1\26\1\33\1\4"+
    "\1\16\1\42\1\31\1\24\1\40\1\4\1\52\1\53\1\37\12\0"+
    "\1\12\252\0\2\21\115\0\1\41\u1ea8\0\1\12\1\12\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\2\4\1\5\1\6\1\7"+
    "\12\3\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\0\1\17\2\20\11\3\1\0\3\3\1\0\6\3"+
    "\1\21\1\0\3\3\1\0\3\3\1\0\6\3\1\0"+
    "\4\3\1\0\4\3\1\0\2\3\1\20\1\3\1\0"+
    "\1\3\1\22\1\0\2\3\1\23\1\0\4\3\1\0"+
    "\4\3\1\0\3\3\1\0\1\3\1\24\1\25\1\24"+
    "\1\25\1\0\1\3\2\26\1\0\1\3\1\0\1\3"+
    "\1\27\1\3\1\0\1\3\1\0\1\3\1\30\1\3"+
    "\1\0\1\3\2\31\2\3\1\0\1\3\1\0\1\3"+
    "\1\22\1\3\2\32\1\0\1\3\1\0\1\3\1\0"+
    "\2\3\1\0\2\33\1\34\1\3\1\0\1\3\1\0"+
    "\2\3\1\0\1\3\2\35\1\3\1\0\1\3\2\36"+
    "\1\3\2\37\1\40\2\41\1\3\1\42";

  private static int [] zzUnpackAction() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\55\0\207\0\264\0\341\0\55"+
    "\0\u010e\0\u013b\0\u0168\0\u0195\0\u01c2\0\u01ef\0\u021c\0\u0249"+
    "\0\u0276\0\u02a3\0\u02d0\0\u02fd\0\55\0\55\0\55\0\55"+
    "\0\55\0\55\0\55\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de"+
    "\0\u040b\0\u0438\0\u0465\0\u0492\0\u04bf\0\u04ec\0\u0519\0\u0546"+
    "\0\u0573\0\u05a0\0\u05cd\0\u05fa\0\u0627\0\u0654\0\u0681\0\u06ae"+
    "\0\u06db\0\u0708\0\u0735\0\u032a\0\u0762\0\u078f\0\u07bc\0\u07e9"+
    "\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7\0\u0924\0\u0951"+
    "\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32\0\u0a5f\0\u0a8c\0\u0ab9"+
    "\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u0b9a\0\u0bc7\0\u0bf4\0\u0c21"+
    "\0\u0762\0\u0c4e\0\u0c7b\0\u0ca8\0\207\0\u0cd5\0\u0d02\0\u0d2f"+
    "\0\207\0\u0d5c\0\u0d89\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a"+
    "\0\u0e97\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2"+
    "\0\u0fff\0\55\0\55\0\207\0\207\0\u102c\0\u1059\0\55"+
    "\0\207\0\u1086\0\u10b3\0\u10e0\0\u110d\0\207\0\u113a\0\u1167"+
    "\0\u1194\0\u11c1\0\u11ee\0\207\0\u121b\0\u1248\0\u1275\0\u12a2"+
    "\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383\0\u13b0\0\u13dd\0\55"+
    "\0\u140a\0\55\0\207\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb"+
    "\0\u1518\0\u1545\0\u1572\0\55\0\207\0\207\0\u159f\0\u15cc"+
    "\0\u15f9\0\u1626\0\u1653\0\u1680\0\u16ad\0\u16da\0\55\0\207"+
    "\0\u1707\0\u1734\0\u1761\0\55\0\207\0\u178e\0\55\0\207"+
    "\0\207\0\55\0\207\0\u17bb\0\207";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\2\1\6\1\7\1\10"+
    "\1\11\1\2\1\4\1\12\1\13\1\14\1\15\1\5"+
    "\1\2\1\5\1\16\1\5\1\17\1\20\3\5\1\21"+
    "\1\22\1\23\3\5\1\24\1\2\1\5\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\3\5\57\0\1\4"+
    "\56\0\4\5\5\0\4\5\1\0\17\5\1\0\1\5"+
    "\7\0\3\5\10\0\1\34\52\0\2\7\1\34\55\0"+
    "\1\35\51\0\1\36\1\37\51\0\4\5\5\0\1\5"+
    "\1\40\2\5\1\0\17\5\1\0\1\5\7\0\3\5"+
    "\4\0\4\5\5\0\2\5\1\41\1\5\1\0\4\5"+
    "\1\42\1\5\1\43\10\5\1\0\1\5\7\0\3\5"+
    "\4\0\4\5\5\0\4\5\1\0\3\5\1\44\4\5"+
    "\1\45\1\5\1\46\2\5\1\47\1\5\1\0\1\5"+
    "\7\0\3\5\4\0\4\5\5\0\2\5\1\50\1\5"+
    "\1\51\1\52\1\5\1\53\3\5\1\54\10\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\4\5\1\55"+
    "\1\56\16\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\13\5\1\57\3\5\1\0\1\5"+
    "\7\0\3\5\4\0\4\5\5\0\2\5\1\60\1\5"+
    "\1\0\17\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\4\5\1\61\12\5\1\0\1\5"+
    "\7\0\3\5\4\0\4\5\5\0\4\5\1\0\4\5"+
    "\1\62\12\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\6\5\1\63\10\5\1\0\1\5"+
    "\7\0\3\5\6\0\2\64\45\0\1\35\2\0\7\35"+
    "\2\0\41\35\10\0\1\65\52\0\2\37\1\65\50\0"+
    "\4\5\5\0\2\5\1\66\1\5\1\0\17\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\4\5\1\0"+
    "\5\5\1\67\11\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\14\5\1\70\2\5\1\71"+
    "\1\72\7\0\3\5\4\0\4\5\5\0\4\5\1\0"+
    "\1\5\1\73\15\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\7\5\1\74\7\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\4\5\1\75"+
    "\1\76\1\77\5\5\1\100\7\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\2\5\1\101\1\5\1\0"+
    "\17\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\4\5\1\0\2\5\1\102\14\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\3\5\1\103\1\0\17\5"+
    "\1\0\1\5\7\0\3\5\16\0\1\104\42\0\4\5"+
    "\5\0\1\5\1\105\2\5\1\0\17\5\1\0\1\5"+
    "\7\0\3\5\4\0\4\5\5\0\1\5\1\106\1\107"+
    "\1\5\1\0\17\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\3\5\1\110\13\5\1\0"+
    "\1\5\7\0\3\5\32\0\1\111\26\0\4\5\5\0"+
    "\4\5\1\0\10\5\1\112\6\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\4\5\1\0\14\5\1\113"+
    "\2\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\1\5\1\114\2\5\1\0\17\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\4\5\1\0\3\5\1\115"+
    "\13\5\1\116\1\117\7\0\3\5\4\0\4\5\5\0"+
    "\1\5\1\72\2\5\1\0\17\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\1\5\1\120\2\5\1\0"+
    "\17\5\1\0\1\5\7\0\3\5\6\0\2\121\51\0"+
    "\4\5\5\0\3\5\1\122\1\0\17\5\1\0\1\5"+
    "\7\0\3\5\4\0\4\5\5\0\4\5\1\123\1\124"+
    "\16\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\4\5\1\0\4\5\1\125\12\5\1\0\1\5\7\0"+
    "\3\5\17\0\1\126\41\0\4\5\5\0\2\5\1\127"+
    "\1\5\1\0\17\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\7\5\1\130\7\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\4\5\1\0"+
    "\4\5\1\131\12\5\1\0\1\5\7\0\3\5\34\0"+
    "\1\132\24\0\4\5\5\0\4\5\1\0\12\5\1\133"+
    "\4\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\4\5\1\0\17\5\1\0\1\5\7\0\2\5\1\134"+
    "\4\0\4\5\5\0\4\5\1\0\6\5\1\135\10\5"+
    "\1\0\1\5\7\0\3\5\4\0\4\5\5\0\1\5"+
    "\1\136\2\5\1\0\17\5\1\0\1\5\7\0\3\5"+
    "\4\0\4\5\5\0\4\5\1\0\3\5\1\125\13\5"+
    "\1\0\1\5\7\0\3\5\4\0\4\5\5\0\4\5"+
    "\1\0\6\5\1\125\10\5\1\0\1\5\7\0\3\5"+
    "\23\0\1\137\35\0\4\5\5\0\4\5\1\0\1\5"+
    "\1\140\15\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\16\5\1\141\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\4\5\1\0\5\5\1\142"+
    "\11\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\4\5\1\0\6\5\1\143\10\5\1\0\1\5\7\0"+
    "\3\5\30\0\1\144\30\0\4\5\5\0\4\5\1\0"+
    "\6\5\1\145\10\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\6\5\1\146\10\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\2\5\1\147"+
    "\1\5\1\0\17\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\150\1\151\16\5\1\0\1\5"+
    "\7\0\3\5\52\0\1\152\1\153\5\0\4\5\5\0"+
    "\4\5\1\0\17\5\1\0\1\5\7\0\1\154\1\155"+
    "\1\5\4\0\4\5\5\0\4\5\1\0\5\5\1\103"+
    "\11\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\4\5\1\156\1\157\16\5\1\0\1\5\7\0\3\5"+
    "\26\0\1\160\32\0\4\5\5\0\4\5\1\0\4\5"+
    "\1\161\12\5\1\0\1\5\7\0\3\5\27\0\1\162"+
    "\31\0\4\5\5\0\4\5\1\0\5\5\1\70\11\5"+
    "\1\0\1\5\7\0\3\5\4\0\4\5\5\0\2\5"+
    "\1\163\1\5\1\0\17\5\1\0\1\5\7\0\3\5"+
    "\17\0\1\164\41\0\4\5\5\0\2\5\1\165\1\5"+
    "\1\0\17\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\4\5\1\166\12\5\1\0\1\5"+
    "\7\0\3\5\4\0\4\5\5\0\1\5\1\167\2\5"+
    "\1\0\17\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\170\1\171\16\5\1\0\1\5\7\0"+
    "\3\5\24\0\1\172\34\0\4\5\5\0\4\5\1\0"+
    "\2\5\1\173\14\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\2\5\1\174\1\5\1\0\17\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\1\5\1\175"+
    "\2\5\1\0\17\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\17\5\1\176\1\177\7\0"+
    "\3\5\17\0\1\200\41\0\4\5\5\0\2\5\1\201"+
    "\1\5\1\0\17\5\1\0\1\5\7\0\3\5\4\0"+
    "\4\5\5\0\4\5\1\0\7\5\1\202\7\5\1\0"+
    "\1\5\7\0\3\5\4\0\4\5\5\0\4\5\1\0"+
    "\10\5\1\203\6\5\1\0\1\5\7\0\3\5\15\0"+
    "\1\204\43\0\4\5\5\0\1\205\3\5\1\0\17\5"+
    "\1\0\1\5\7\0\3\5\23\0\1\206\35\0\4\5"+
    "\5\0\4\5\1\0\1\5\1\207\15\5\1\0\1\5"+
    "\7\0\3\5\26\0\1\210\32\0\4\5\5\0\4\5"+
    "\1\0\10\5\1\211\6\5\1\0\1\5\7\0\3\5"+
    "\16\0\1\212\42\0\4\5\5\0\1\5\1\213\2\5"+
    "\1\0\17\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\214\1\215\16\5\1\0\1\5\7\0"+
    "\3\5\25\0\1\216\33\0\4\5\5\0\4\5\1\0"+
    "\3\5\1\217\13\5\1\0\1\5\7\0\3\5\25\0"+
    "\1\220\33\0\4\5\5\0\4\5\1\0\3\5\1\221"+
    "\13\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\2\5\1\222\1\5\1\0\17\5\1\0\1\5\7\0"+
    "\3\5\31\0\1\223\27\0\4\5\5\0\4\5\1\0"+
    "\7\5\1\103\7\5\1\0\1\5\7\0\3\5\25\0"+
    "\1\224\33\0\4\5\5\0\4\5\1\0\3\5\1\225"+
    "\13\5\1\0\1\5\7\0\3\5\4\0\4\5\5\0"+
    "\4\5\1\0\4\5\1\226\12\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\4\5\1\0\14\5\1\227"+
    "\2\5\1\0\1\5\7\0\3\5\26\0\1\230\32\0"+
    "\4\5\5\0\4\5\1\0\4\5\1\231\12\5\1\0"+
    "\1\5\7\0\3\5\17\0\1\232\41\0\4\5\5\0"+
    "\2\5\1\233\1\5\1\0\17\5\1\0\1\5\7\0"+
    "\3\5\4\0\4\5\5\0\1\234\3\5\1\0\17\5"+
    "\1\0\1\5\7\0\3\5\26\0\1\235\32\0\4\5"+
    "\5\0\4\5\1\0\4\5\1\236\12\5\1\0\1\5"+
    "\7\0\3\5\25\0\1\162\33\0\4\5\5\0\4\5"+
    "\1\0\3\5\1\70\13\5\1\0\1\5\7\0\3\5"+
    "\26\0\1\237\32\0\4\5\5\0\4\5\1\0\4\5"+
    "\1\240\12\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\5\5\1\241\11\5\1\0\1\5"+
    "\7\0\3\5\30\0\1\210\30\0\4\5\5\0\2\5"+
    "\1\125\1\5\1\0\17\5\1\0\1\5\7\0\3\5"+
    "\32\0\1\242\26\0\4\5\5\0\4\5\1\0\10\5"+
    "\1\243\6\5\1\0\1\5\7\0\3\5\16\0\1\244"+
    "\42\0\4\5\5\0\1\5\1\245\2\5\1\0\17\5"+
    "\1\0\1\5\7\0\3\5\4\0\4\5\5\0\4\5"+
    "\1\0\2\5\1\246\14\5\1\0\1\5\7\0\3\5"+
    "\16\0\1\247\42\0\4\5\5\0\1\5\1\250\2\5"+
    "\1\0\17\5\1\0\1\5\7\0\3\5\4\0\4\5"+
    "\5\0\4\5\1\0\4\5\1\251\12\5\1\0\1\5"+
    "\7\0\3\5\26\0\1\252\32\0\4\5\5\0\4\5"+
    "\1\0\4\5\1\253\12\5\1\0\1\5\7\0\3\5"+
    "\4\0\4\5\5\0\4\5\1\0\3\5\1\254\13\5"+
    "\1\0\1\5\7\0\3\5\4\0\4\5\5\0\4\5"+
    "\1\0\4\5\1\255\12\5\1\0\1\5\7\0\3\5";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6120];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\3\1\1\11\14\1\7\11"+
    "\1\0\14\1\1\0\3\1\1\0\7\1\1\0\3\1"+
    "\1\0\3\1\1\0\6\1\1\0\4\1\1\0\4\1"+
    "\1\0\4\1\1\0\2\1\1\0\3\1\1\0\4\1"+
    "\1\0\4\1\1\0\3\1\1\0\1\1\2\11\2\1"+
    "\1\0\1\1\1\11\1\1\1\0\1\1\1\0\3\1"+
    "\1\0\1\1\1\0\3\1\1\0\5\1\1\0\1\1"+
    "\1\0\1\1\1\11\1\1\1\11\1\1\1\0\1\1"+
    "\1\0\1\1\1\0\2\1\1\0\1\11\3\1\1\0"+
    "\1\1\1\0\2\1\1\0\1\1\1\11\2\1\1\0"+
    "\1\1\1\11\2\1\1\11\2\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[173];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline + 1, yycolumn + 1);
    }
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline + 1, yycolumn + 1, value);
    }
    private LinkedList<String> listaErrores;
public static Map<String, List<OperadorInfo>> operadoresInfo = new HashMap<>();
    private void addOperadorInfo(String operador, int linea, int columna) {
        operadoresInfo.computeIfAbsent(operador, k -> new ArrayList<>())
                      .add(new OperadorInfo(linea, columna, operador + " " + linea + ":" + columna));
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    listaErrores = new LinkedList<>();
    yybegin(YYINITIAL);
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(sym.EOF);
            }  // fall though
            case 174: break;
            default:
          { return new java_cup.runtime.Symbol(sym.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { String errorMsg = "Error lexico: Caracter invalido <" + yytext() + "> en linea " + (yyline+1) + ", columna " + (yycolumn+1);
        listaErrores.add(errorMsg);
        System.out.println(errorMsg);
            } 
            // fall through
          case 35: break;
          case 2: 
            { /* ignorar */
            } 
            // fall through
          case 36: break;
          case 3: 
            { return symbol(sym.IDENTIFICADOR, yytext());
            } 
            // fall through
          case 37: break;
          case 4: 
            { return symbol(sym.ENTEROS, Integer.parseInt(yytext()));
            } 
            // fall through
          case 38: break;
          case 5: 
            { return symbol(sym.PUNTO);
            } 
            // fall through
          case 39: break;
          case 6: 
            { return symbol(sym.DIVISION);
            } 
            // fall through
          case 40: break;
          case 7: 
            { return symbol(sym.RESTA);
            } 
            // fall through
          case 41: break;
          case 8: 
            { return symbol(sym.SUMA);
            } 
            // fall through
          case 42: break;
          case 9: 
            { return symbol(sym.MULTIPLICACION);
            } 
            // fall through
          case 43: break;
          case 10: 
            { return symbol(sym.PARENTESIS_ABIERTO);
            } 
            // fall through
          case 44: break;
          case 11: 
            { return symbol(sym.PARENTESIS_CERRADO);
            } 
            // fall through
          case 45: break;
          case 12: 
            { return symbol(sym.COMA);
            } 
            // fall through
          case 46: break;
          case 13: 
            { return symbol(sym.IGUAL);
            } 
            // fall through
          case 47: break;
          case 14: 
            { return symbol(sym.PUNTO_COMA);
            } 
            // fall through
          case 48: break;
          case 15: 
            { /* ignore comments */
            } 
            // fall through
          case 49: break;
          case 16: 
            { return symbol(sym.NUMERO, Double.parseDouble(yytext()));
            } 
            // fall through
          case 50: break;
          case 17: 
            { return symbol(sym.DECIMAL, Double.parseDouble(yytext()));
            } 
            // fall through
          case 51: break;
          case 18: 
            { return symbol(sym.COLOR, yytext());
            } 
            // fall through
          case 52: break;
          case 19: 
            { return symbol(sym.ALTO);
            } 
            // fall through
          case 53: break;
          case 20: 
            { return symbol(sym.POSX);
            } 
            // fall through
          case 54: break;
          case 21: 
            { return symbol(sym.POSY);
            } 
            // fall through
          case 55: break;
          case 22: 
            { return symbol(sym.RADIO);
            } 
            // fall through
          case 56: break;
          case 23: 
            { return symbol(sym.ANCHO);
            } 
            // fall through
          case 57: break;
          case 24: 
            { return symbol(sym.ANIM_TIPO_CURVA, yytext());
            } 
            // fall through
          case 58: break;
          case 25: 
            { return symbol(sym.LINEA);
            } 
            // fall through
          case 59: break;
          case 26: 
            { return symbol(sym.ANIMAR);
            } 
            // fall through
          case 60: break;
          case 27: 
            { return symbol(sym.ANIM_TIPO_LINEAL, yytext());
            } 
            // fall through
          case 61: break;
          case 28: 
            { return symbol(sym.OBJETO);
            } 
            // fall through
          case 62: break;
          case 29: 
            { return symbol(sym.CIRCULO);
            } 
            // fall through
          case 63: break;
          case 30: 
            { return symbol(sym.GRAFICAR);
            } 
            // fall through
          case 64: break;
          case 31: 
            { return symbol(sym.ANTERIOR);
            } 
            // fall through
          case 65: break;
          case 32: 
            { return symbol(sym.CUADRADO);
            } 
            // fall through
          case 66: break;
          case 33: 
            { return symbol(sym.POLIGONO);
            } 
            // fall through
          case 67: break;
          case 34: 
            { return symbol(sym.RECTANGULO);
            } 
            // fall through
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalizadorLexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalizadorLexico scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalizadorLexico(reader);
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
