
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package Gramaticas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LINEA = 6;
  public static final int RADIO = 30;
  public static final int MULTIPLICACION = 17;
  public static final int PARENTESIS_ABIERTO = 19;
  public static final int IGUAL = 22;
  public static final int DECIMAL = 26;
  public static final int DIVISION = 18;
  public static final int SUMA = 15;
  public static final int ANIM_TIPO_CURVA = 14;
  public static final int ANIMAR = 8;
  public static final int COLOR = 12;
  public static final int CUADRADO = 4;
  public static final int OBJETO = 9;
  public static final int GRAFICAR = 2;
  public static final int PARENTESIS_CERRADO = 20;
  public static final int COMA = 21;
  public static final int ENTEROS = 25;
  public static final int EOF = 0;
  public static final int ANCHO = 31;
  public static final int ALTO = 32;
  public static final int OBJETO_ANTERIOR = 11;
  public static final int NUMERO = 27;
  public static final int error = 1;
  public static final int POLIGONO = 7;
  public static final int IDENTIFICADOR = 24;
  public static final int CIRCULO = 3;
  public static final int PUNTO_COMA = 23;
  public static final int ANTERIOR = 10;
  public static final int ANIM_TIPO_LINEAL = 13;
  public static final int RECTANGULO = 5;
  public static final int POSY = 29;
  public static final int POSX = 28;
  public static final int RESTA = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "LINEA",
  "POLIGONO",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "OBJETO_ANTERIOR",
  "COLOR",
  "ANIM_TIPO_LINEAL",
  "ANIM_TIPO_CURVA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "COMA",
  "IGUAL",
  "PUNTO_COMA",
  "IDENTIFICADOR",
  "ENTEROS",
  "DECIMAL",
  "NUMERO",
  "POSX",
  "POSY",
  "RADIO",
  "ANCHO",
  "ALTO"
  };
}

